var require = {
    baseUrl: '../js/',
    paths: {
        'main': 'background/main',
        'error': 'background/error',
        'background': 'background/background',
        'playerState': 'enum/playerState',
        'repeatButtonState': 'enum/repeatButtonState',
        'dataSource': 'enum/dataSource',
        'player': 'background/player',
        'playlistItem': 'background/playlistItem',
        'playlistItems': 'background/playlistItems',
        'folder': 'background/folder',
        'folders': 'background/folders',
        'playlist': 'background/playlist',
        'playlists': 'background/playlists',
        'youTubePlayerAPI': 'background/model/youTubePlayerAPI',
        'video': 'background/video',
        'videos': 'background/videos',
        'youTubeDataAPI': 'youTubeDataAPI',
        'utility': 'background/utility',
        'jquery': 'thirdParty/jquery',
        'levenshtein': 'thirdParty/levenshtein',
        'underscore': 'thirdParty/underscore',
        'user': 'background/user',
        'backbone': 'thirdParty/backbone',
        'backgroundManager': 'background/backgroundManager',
        'settings': 'background/settings',
        'pushMessageManager': 'background/pushMessageManager',
        'iconManager': 'background/iconManager',
        'spin': 'thirdParty/jquery.spin',
        'shareCode': 'background/shareCode',
        'shareableEntityType': 'enum/shareableEntityType',
        
        'streamItems': 'background/collection/streamItems',
        'streamItem': 'background/model/streamItem'
    }
};