var require = {
    baseUrl: '../js/',
    paths: {
        'main': 'background/main',
        'error': 'background/error',
        'programState': 'programState',
        'background': 'background/background',
        'playerStates': 'playerStates',
        'repeatButtonStates': 'repeatButtonStates',
        'dataSources': 'dataSources',
        'player': 'background/player',
        'playlistItem': 'background/playlistItem',
        'playlistItems': 'background/playlistItems',
        'stream': 'background/stream',
        'streams': 'background/streams',
        'playlist': 'background/playlist',
        'playlists': 'background/playlists',
        'youTubePlayerAPI': 'youTubePlayerAPI',
        'video': 'background/video',
        'videos': 'background/videos',
        'ytHelper': 'ytHelper',
        'helpers': 'helpers',
        'jquery': 'thirdParty/jquery',
        'levenshtein': 'thirdParty/levenshtein',
        'underscore': 'thirdParty/underscore',
        'user': 'background/user',
        'backbone': 'thirdParty/backbone',
        'backgroundManager': 'background/backgroundManager',
        'localStorageManager': 'background/localStorageManager',
        'pushMessageManager': 'background/pushMessageManager',
        'iconManager': 'background/iconManager',
        'spin': 'thirdParty/jquery.spin',
        'shareCode': 'background/shareCode'
    }
};