var require = {
    baseUrl: '../js/',
    paths: {
        'main': 'background/main',
        'error': 'background/error',
        'programState': 'programState',
        'background': 'background/background',
        'playerState': 'enum/playerState',
        'repeatButtonState': 'enum/repeatButtonState',
        'dataSource': 'enum/dataSource',
        'player': 'background/player',
        'playlistItem': 'background/playlistItem',
        'playlistItems': 'background/playlistItems',
        'folder': 'background/folder',
        'folders': 'background/folders',
        'playlist': 'background/playlist',
        'playlists': 'background/playlists',
        'youTubePlayerAPI': 'youTubePlayerAPI',
        'video': 'background/video',
        'videos': 'background/videos',
        'ytHelper': 'ytHelper',
        'helpers': 'helpers',
        'jquery': 'thirdParty/jquery',
        'levenshtein': 'thirdParty/levenshtein',
        'underscore': 'thirdParty/underscore',
        'user': 'background/user',
        'backbone': 'thirdParty/backbone',
        'backgroundManager': 'background/backgroundManager',
        'entityAction': 'background/entityAction',
        'entityType': 'background/entityType',
        'settingsManager': 'background/settingsManager',
        'pushMessageManager': 'background/pushMessageManager',
        'pushMessage': 'background/pushMessage',
        'iconManager': 'background/iconManager',
        'spin': 'thirdParty/jquery.spin',
        'shareCode': 'background/shareCode',
        'shareableEntityType': 'enum/shareableEntityType',
        
        'streamItems': 'background/collection/streamItems',
        'streamItem': 'background/model/streamItem'
    }
};