var require = {
    baseUrl: '../ChromeExtension/js/',
    paths: {
        'main': 'background/main',
        'programState': 'programState',
        'background': 'background/background',
        'playerStates': 'playerStates',
        'player': 'background/player',
        'playlist': 'background/playlist',
        'playlists': 'background/playlists',
        'playlistManager': 'background/playlistManager',
        'loginManager': 'background/loginManager',
        'videoManager': 'background/videoManager',
        'playerBuilder': 'playerBuilder',
        'ytPlayerApiHelper': 'thirdParty/ytPlayerApiHelper',
        'onYouTubePlayerApiReady': 'thirdParty/onYouTubePlayerApiReady',
        'video': 'video',
        'videos': 'videos',
        'ytHelper': 'ytHelper',
        'helpers': 'helpers',
        'jquery': 'thirdParty/jquery',
        'geoplugin': 'thirdParty/geoplugin',
        'levenshtein': 'thirdParty/levenshtein',
        'underscore': 'thirdParty/underscore',
        'user': 'background/user',
        'oauth2': 'thirdParty/oauth2/oauth2',
        'playlistItem': 'background/playlistItem',
        'playlistItems': 'background/playlistItems',
        'playlistItemsHistory': 'background/playlistItemsHistory',
        'backbone': 'thirdParty/backbone'
    }
};